OperatorStationServer/urls.py
from django.conf.urls import include,url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('agent.urls')),
]

agent/urls.py
from django.conf.urls import url
from django.urls import path

from rest_framework.urlpatterns import format_suffix_patterns

from . import views

app_name = 'agent'
urlpatterns = [
    path('api/', views.API.as_view()),
    path('api/takeoff/', views.Takeoff.as_view(), name='takeoff'),
    path('api/direction/', views.SetDirection.as_view(), name='direction'),
    path('api/land/', views.Land.as_view(), name='land'),
    path('api/rtl/', views.ReturnToLaunch.as_view(), name='rtl'),
    path('api/command/<int:pk>/', views.LatestCommand.as_view(), name='command'),
    path('api/list/', views.AgentList.as_view(), name='agent_list'),
    path('api/agent/<int:pk>/', views.AgentDetails.as_view(), name='details'),
    path('api/agent/new/', views.CreateAgent.as_view(), name='new_agent'),
    url(r'^agent/', views.agents, name='agents'),
    url(r'^ui/update/', views.update, name='update'),
    url(r'^ui/direction/', views.set_direction, name='set_direction'),
    url(r'^ui/reset/', views.reset, name='reset_agents'),
    url(r'^ui/beacon/', views.beacon, name='beacon'),
    url(r'^', views.users, name='users'),
]

urlpatterns = format_suffix_patterns(urlpatterns)

agent/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models
from django.utils import timezone

# Create your models here.

class Agent(models.Model):
    client_timestamp = models.DateTimeField('client time stamp')
    server_timestamp = models.DateTimeField('server reception time')
    latitude = models.FloatField()
    longitude = models.FloatField()
    altitude = models.FloatField()
    azimuth = models.FloatField()
    armed = models.BooleanField()
    bat_volt = models.FloatField('Battery Voltage')
    gps_fix = models.IntegerField()
    gps_hdop = models.FloatField()
    mode = models.CharField(max_length=20)
    llc_message = models.CharField(max_length=200)
    llc_state = models.CharField(max_length=20)
    hlc_state = models.CharField(max_length=20)
    mc_state = models.CharField(max_length=20)
    
    def __str__(self):
        return "Agent "+str(self.id)

DictCommand = ['None','Takeoff','Land','GoHome','SetDirection']

class Operator(models.Model):
    command = models.IntegerField()
    direction = models.FloatField('Azimuth in degrees')
    server_timestamp = models.DateTimeField('server reception time')
    
    def __str__(self):
        return DictCommand[self.command]
    
    def NoCommand(self):
        self.command = 0
        self.direction = -1
        self.server_timestamp = timezone.now()
        self.save()
        
    def Takeoff(self):
        self.command = 1
        self.direction = -1
        self.server_timestamp = timezone.now()
        self.save()
        
    def Land(self):
        self.command = 2
        self.direction = -1
        self.server_timestamp = timezone.now()
        self.save()

    def RTL(self):
        self.command = 3
        self.direction = -1
        self.server_timestamp = timezone.now()
        self.save()
        
    def SetDirection(self,direction):
        self.command = 4
        self.direction = direction
        self.server_timestamp = timezone.now()
        self.save()        
        
    def isRelevant(self):
        timedeltaFromLastCommand = timezone.now() - self.server_timestamp
        return ((timedeltaFromLastCommand.seconds < 3) and (0 <= timedeltaFromLastCommand.seconds))

agent/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

import json
import datetime
import pytz
from math import sin, cos, pi

from geographiclib.geodesic import Geodesic

from django.utils import timezone
from django.shortcuts import render
from django.conf import settings
from django.http import HttpResponse, HttpResponseRedirect

from rest_framework import generics, renderers
from rest_framework.decorators import api_view
from rest_framework.views import APIView
from rest_framework.response import Response
from rest_framework.reverse import reverse

from agent.models import Agent, Operator
from agent.serializers import AgentSerializer, OperatorSerializer

no_id = 4294967295 # largest integer
visibilityDistance = 100000 #meters
alpha = 40  #degrees


#---------------------------------- Helper functions ---------------------------------

def detected_others(agent):
    for other in Agent.objects.exclude(pk=agent.id):
        g = Geodesic.WGS84.Inverse(agent.latitude, agent.longitude, other.latitude, other.longitude)
        if ((visibilityDistance > g['s12']) and (cos((g['azi1']*pi/180 - agent.azimuth)) > cos(alpha*pi/360))):
            return True
    return False;

def get_latest_operator():
    if (False == Operator.objects.exists()):
        user = Operator()
        user.NoCommand()
    else:
        user = Operator.objects.order_by('-server_timestamp')[0]
    return user

#--------------------------------- API ----------------------------------

class API(APIView):
    """
    NeMALA / Operator Station API
    """
    def get(self, request, format=None):
        reply = {
            'Takeoff': reverse('agent:takeoff', request=request, format=format),
            'Set Direction': reverse('agent:direction', request=request, format=format),
            'Land': reverse('agent:land', request=request, format=format),
            'Return to Launch': reverse('agent:rtl', request=request, format=format),
            'Last Operator Command': reverse('agent:command', args=('1',), request=request, format=format),
            'Agent List': reverse('agent:agent_list', request=request, format=format),
            'New Agent': reverse('agent:new_agent', request=request, format=format)
            }
        for agent in Agent.objects.order_by('id'):
            str_name = agent.__str__() + ' Details'
            reply[str_name] = reverse('agent:details', args=(agent.id,), request=request, format=format)
        return Response(reply)

class Takeoff(APIView):
    """
    Operator Command to all listening agents to perform a takeoff
    """
    def post(self, request, format=None):
        user = get_latest_operator()
        user.Takeoff()
        return Response(status=200)


class SetDirection(APIView):
    """
    Operator Command to all listening agents to move towards some direction \
    (direction x in degrees, 0 <= x < 360) for 3 seconds.\
    Example : {"direction": 64}
    """
    def post(self, request, format=None):
        reply = Response(status=200)
        direction = 0
        try:
            direction = float(request.data['direction'])
        except Exception as e:
            reply = Response(data=e.__str__(), status=400)
        else:
            if ( (0 <= direction) and (360 > direction) ):
                user = get_latest_operator()
                user.SetDirection(direction)
            else:
                reply = Response(data='Azimuth out of bounds.', status=400)
        return reply

class Land(APIView):
    """
    Operator Command to all listening agents to land
    """
    def post(self, request, format=None):
        user = get_latest_operator()
        user.Land()
        return Response(status=200)
    
class ReturnToLaunch(APIView):
    """
    Operator Command to all listening agents to return to launch
    """
    def post(self, request, format=None):
        user = get_latest_operator()
        user.RTL()
        return Response(status=200)

class LatestCommand(generics.RetrieveAPIView):
    """
    Latest Command Input
    """
    queryset = Operator.objects.all()
    serializer_class = OperatorSerializer

class AgentList(generics.ListAPIView):
    """
    A list of current active agents
    """
    queryset = Agent.objects.all()
    serializer_class = AgentSerializer
    
class AgentDetails(generics.RetrieveUpdateDestroyAPIView):
    """
    Manipulate a specific agent or beacon
    """
    queryset = Agent.objects.all()
    serializer_class = AgentSerializer
    
class CreateAgent(generics.CreateAPIView):
    """
    Create a new agent or beacon
    """
    queryset = Agent.objects.all()
    serializer_class = AgentSerializer

#--------------------------------------------- UI -------------------------------------------

def users(request):
    agent_list = Agent.objects.order_by('id')
    context = {'agent_list': agent_list, 'google_maps_key': settings.GOOGLE_MAPS_API_KEY}
    return render(request, 'agent/operator.html', context)

def update(request):
    """
    Responds to a user's Get request with the latest Operator's command and Agent list.
    """
    agent_list = Agent.objects.order_by('id')
    context = {'server_time' : timezone.now() , 'agent_list': agent_list}
    return render(request, 'agent/update.html', context)

def set_direction(request):
    """
    Similar to update, just accepts a POST with a direction command.
    """
    reply = HttpResponse(status=405)
    if ('POST' == request.method):
        user = get_latest_operator()
        user.SetDirection(request.POST['direction'])
        reply = update(request)
    return reply

def reset(request):
    """
    Expects a POST request to remove all inactive agents and beacons
    """
    reply = HttpResponse(status=405)
    if ('POST' == request.method):
        Agent.objects.all().delete()
        reply = HttpResponseRedirect(reverse('agent:users'))
    return reply

def beacon(request):
    """
    Adds a phantom agent
    """
    reply = HttpResponse(status=405)
    if ('POST' == request.method):
        agent = Agent(
            client_timestamp = timezone.now(),
            server_timestamp = timezone.now(),
            latitude = float(request.POST['lat']),
            longitude = float(request.POST['lon']),
            altitude = 0,
            azimuth = 3.14,
            armed = 0,
            bat_volt = 0,
            gps_fix = 0,
            gps_hdop = 0,
            mode = "BEACON",
            llc_message = "this",
            llc_state = "is",
            hlc_state = "a",
            mc_state = "beacon"
        )
        agent.save()
        reply = HttpResponseRedirect(reverse('agent:users'))
    return reply

#--------------------------------------- Agent -----------------------------------------------

@api_view(['POST'])
def agents(request):
    """
    Responds to an agent's POST request with the latest Operator's command.
    """
    reply = HttpResponse(content='POST expected', status=405)
    if ('POST' == request.method):
        dictMessage = json.loads(request.POST['root'])
        
        #print(request.POST['root'])
        
        agentId = int(dictMessage['Message']['Header']['Topic'])
        unaware = datetime.datetime.strptime(dictMessage['Message']['Header']['TimeStamp'],"%Y-%m-%dT%H:%M:%S.%f")
        now_aware = unaware.replace(tzinfo=pytz.UTC)
        agent = Agent(  
                        client_timestamp = now_aware,
                        server_timestamp = timezone.now(),
                        latitude = float(dictMessage['Message']['Body']['Lat']),
                        longitude = float(dictMessage['Message']['Body']['Lon']),
                        altitude = float(dictMessage['Message']['Body']['Alt']),
                        azimuth = float(dictMessage['Message']['Body']['Yaw']),
                        armed = (1 == int(dictMessage['Message']['Body']['Armed'])),
                        bat_volt = float(dictMessage['Message']['Body']['Volt']),
                        gps_fix = int(dictMessage['Message']['Body']['GpsFix']),
                        gps_hdop = float(dictMessage['Message']['Body']['GpsHdop']),
                        mode = dictMessage['Message']['Body']['Mode'],
                        llc_message = dictMessage['Message']['Body']['LlcMessage'],
                        llc_state = dictMessage['Message']['Body']['LlcState'],
                        hlc_state = dictMessage['Message']['Body']['HlcState'],
                        mc_state = dictMessage['Message']['Body']['McState']
                    )
        
        if (no_id == agentId):
            agent.id = None
        else:
            agent.id = agentId
        
        agent.save()
        
        # Check if other agents are in this agent's field of view
        detected = detected_others(agent)
        
        user = get_latest_operator()

        if (False == user.isRelevant()):
                user.NoCommand()

        reply = {
            'id':  agent.id,
            'command': user.command,
            'direction': user.direction,
            'payload':
            {
                'detected': detected
            },
            'timestamp': user.server_timestamp.__str__()
            }
        #print json.dumps(reply)
        reply = HttpResponse(json.dumps(reply))
    return reply

agent/templates/agent/operator.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>Alate</title>
    
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    
    <!-- Optional meta tags -->
    <meta name="description" content="An Operator Station for Swarming Agents">
    <meta name="author" content="dave">
    
    <!-- Distribution Includes -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="http://yui.yahooapis.com/3.18.1/build/yui/yui-min.js"></script>
    <script src="https://maps.googleapis.com/maps/api/js?key={{ google_maps_key }}"></script>


    <!-- Static Custom Look & Feel -->
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'agent/style.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'agent/grid.css' %}" />
	<link rel="stylesheet" type="text/css" href="{% static 'agent/collapsible.css' %}" />
	<link rel="stylesheet" type="text/css" href="{% static 'agent/direction_control.css' %}" />
	<link rel="shortcut icon" href="{% static 'agent/favicon.ico' %}" />
    <script src="{% static 'agent/knob_customization.js' %}"></script>
    <script src="{% static 'agent/collapsible.js' %}"></script>
    <script src="{% static 'agent/main.js' %}"></script>
    <script src="{% static 'agent/map.js' %}"></script>
    
	<!-- On document load, ready all JS functionality -->
	<script>
	$(document).ready(function()
	{
		$("#direction_value").hide()
		$("#beacon").hide()

		var coll = document.getElementsByClassName("collapsible");
		var i;
		for (i = 0; i < coll.length; i++)
		{
			MakeCollapsible(coll[i]);
		}

		$("#status").hide()
	    $("#status").click(function(event)
	   	{
	    	event.preventDefault();
	    	if (document.getElementById("directionCheck").checked)
	    	{
	    		$.post("{% url 'agent:set_direction' %}", 
	    		{
	    			direction: $("#direction_value").val(),
	    			csrfmiddlewaretoken: $("input[name='csrfmiddlewaretoken']").val()
	    		},
	    		function(response)
	    		{
	    			UpdateStatus(response);
	    		});	 
	    	}
	    	else
	    	{
				$.get("{% url 'agent:update' %}", function(response)
	    		{
	    			UpdateStatus(response);
	    		});	  	
	    	}  
	    });
		
		$("#takeoff").click(function(event)
	   	{
	    	event.preventDefault();
    		$.post("{% url 'agent:takeoff' %}",
				{
					csrfmiddlewaretoken: $("input[name='csrfmiddlewaretoken']").val()
				}
			);
	    });
		
		$("#land").click(function(event)
	   	{
	    	event.preventDefault();
    		$.post("{% url 'agent:land' %}",
				{
					csrfmiddlewaretoken: $("input[name='csrfmiddlewaretoken']").val()
				}
			);
	    });
		
		$("#RTL").click(function(event)
	   	{
	    	event.preventDefault();
    		$.post("{% url 'agent:rtl' %}",
				{
					csrfmiddlewaretoken: $("input[name='csrfmiddlewaretoken']").val()
				}
			);
	    });
		
		var agentData = document.getElementsByClassName("agent_data")
		if (0 < agentData.length)
		{
			SetupMap(Number(agentData[0].querySelector("#lat").innerHTML), Number(agentData[0].querySelector("#lon").innerHTML));
		}
		else{
			SetupMap();
		}
		
		
	    window.setInterval(function(){
	    	document.getElementById("status").click();
	    	}, 1000);
	});
	</script>
  </head>
  
  <body>
  	<div class="grid-container" id="main_container">
  		<div class="header">
  			<h2>Control the Swarm</h2>
  		</div>
  		<div class="left" id="AgentList" style="background-color:#aaa;">
  			<h2>Active Agents</h2>
  			<form action="{% url 'agent:reset_agents' %}" method="post">
  				{% csrf_token %}</input>
  				<input class="full_width" type="submit" value="Reset Agent Table" />
  			</form>
  			{% if agent_list %}
  				{% for agent in agent_list %}
  			<button class="collapsible" id="{{ agent }}">{{ agent }}</button>
  			<div class="agent_data" id="{{ agent }} data">
  				<table>
  					<tr>
  						<th>Client Time Stamp:</th><td id="client_timestamp">{{ agent.client_timestamp | date:"Y-m-d H:i:s.u" }}</td>
  					</tr>
  					<tr>
  						<th>Server Reception Time:</th><td id="server_timestamp">{{ agent.server_timestamp | date:"Y-m-d H:i:s.u" }}</td>
  					</tr>
  					<tr>
  						<th>Latitude:</th><td id="lat">{{agent.latitude}}</td>
  					</tr>
  					<tr>
  						<th>Longitude:</th><td id="lon">{{agent.longitude}}</td>
  					</tr>
  					<tr>
  						<th>Altitude:</th><td id="alt">{{agent.altitude}}</td>
  					</tr>
  					<tr>
  						<th>Azimuth:</th><td id="azi">{{agent.azimuth}}</td>
  					</tr>
  					<tr>
  						<th>Armed:</th><td>{{agent.armed}}</td>
  					</tr>
  					<tr>
  						<th>Battery Voltage:</th><td>{{agent.bat_volt}}</td>
  					</tr>
  					<tr>
  						<th>GPS Fix:</th><td>{{agent.gps_fix}} </td>
  					</tr>
  					<tr>
  						<th>GPS HDOP:</th><td>{{agent.gps_hdop}}</td>
  					</tr>
  					<tr>
  						<th>Mode:</th><td>{{agent.mode}}</td>
  					</tr>
  					<tr>
  						<th>Low Level Control Message:</th><td>{{agent.llc_message}}</td>
  					</tr>
  					<tr>
  						<th>Low Level Control State:</th><td id="llc_state">{{agent.llc_state}}</td>
  					</tr>
  					<tr>
  						<th>High Level Control State:</th><td id="hlc_state">{{agent.hlc_state}}</td>
  					</tr>
  					<tr>
  						<th>Mission Control State:</th><td id="mc_state">{{agent.mc_state}}</td>
  					</tr>
  				</table>
			</div>
				{% endfor %}
			{% else %}
			<p>No active agents.</p>
			{% endif %}
  		</div> <!-- AgentList -->
  		<div class="middle" id="Display" style="background-color:#bbb;">
			<div id="map"></div>
  		</div><!-- Display -->  
		<div class="right" id="Action" style="background-color:#ccc;">
			<h2>Actions</h2>
			<form action="{% url 'agent:takeoff' %}" method="post"  id="takeoff">
				{% csrf_token %}</input>
				<input class="full_width" type="submit" value="Take off!" />
			</form>
			
			<div class="direction_control">
				<div class="direction_control_toggle">
					<label class="switch">
						<input type="checkbox" id="directionCheck"/>
						<span class="slider"></span>
					</label>
				</div>
				<div class="direction_control_dial">
					<div  class="yui3-skin-sam"> <!-- You need this skin class -->
						<div id="direction_knob"></div>
					</div>
				</div>
				<input id="direction_value" type="text" value=""/>
			</div>
			
			<form action="{% url 'agent:land' %}" method="post" id="land">
				{% csrf_token %}</input>
				<input class="full_width" type="submit" value="Land" />
			</form>
				
			<form action="{% url 'agent:rtl' %}" method="post" id="RTL">
				{% csrf_token %}</input>
				<input class="full_width" type="submit" value="Return To Launch" />
			</form>
			
			<form action="{% url 'agent:update' %}" method="get" id="status">
				<input class="full_width" type="submit" value="Get Status" />
			</form>
			
			<form action="{% url 'agent:beacon' %}" method="post" id="beacon">
				{% csrf_token %}</input>
				<input class="full_width" type="text" name="lat" id="beacon_lat"/>
				<input class="full_width" type="text" name="lon" id="beacon_lon"/>
				<input class="full_width" type="submit" value="Beacon" />
			</form>

	  	</div><!-- Action -->
	  	<div class="footer">
	  		<p>© 2018 David Dovrat - IIT License</p>
	  	</div>
	</div><!-- main_container -->
  </body>
  
</html>

agent/templates/agent/update.html
<div class="left" id="AgentList" style="background-color:#aaa;">
	<h2>Active Agents</h2>
	<form action="{% url 'agent:reset_agents' %}" method="post">
		{% csrf_token %}</input>
		<input class="full_width" type="submit" value="Reset Agent Table" />
	</form>
	<div id="server_time">{{server_time | date:"Y-m-d H:i:s.u"}}</div>
	{% if agent_list %}
		{% for agent in agent_list %}
	<button class="collapsible" id="{{ agent }}">{{ agent }}</button>
	<div class="agent_data" id="{{ agent }} data">
  				<table>
  					<tr>
  						<th>Client Time Stamp:</th><td id="client_timestamp">{{ agent.client_timestamp | date:"Y-m-d H:i:s.u" }}</td>
  					</tr>
  					<tr>
  						<th>Server Reception Time:</th><td id="server_timestamp">{{ agent.server_timestamp | date:"Y-m-d H:i:s.u" }}</td>
  					</tr>
  					<tr>
  						<th>Latitude:</th><td id="lat">{{agent.latitude}}</td>
  					</tr>
  					<tr>
  						<th>Longitude:</th><td id="lon">{{agent.longitude}}</td>
  					</tr>
  					<tr>
  						<th>Altitude:</th><td id="alt">{{agent.altitude}}</td>
  					</tr>
  					<tr>
  						<th>Azimuth:</th><td id="azi">{{agent.azimuth}}</td>
  					</tr>
  					<tr>
  						<th>Armed:</th><td>{{agent.armed}}</td>
  					</tr>
  					<tr>
  						<th>Battery Voltage:</th><td>{{agent.bat_volt}}</td>
  					</tr>
  					<tr>
  						<th>GPS Fix:</th><td>{{agent.gps_fix}} </td>
  					</tr>
  					<tr>
  						<th>GPS HDOP:</th><td>{{agent.gps_hdop}}</td>
  					</tr>
  					<tr>
  						<th>Mode:</th><td>{{agent.mode}}</td>
  					</tr>
  					<tr>
  						<th>Low Level Control Message:</th><td>{{agent.llc_message}}</td>
  					</tr>
  					<tr>
  						<th>Low Level Control State:</th><td id="llc_state">{{agent.llc_state}}</td>
  					</tr>
  					<tr>
  						<th>High Level Control State:</th><td id="hlc_state">{{agent.hlc_state}}</td>
  					</tr>
  					<tr>
  						<th>Mission Control State:</th><td id="mc_state">{{agent.mc_state}}</td>
  					</tr>
  				</table>
	</div>
		{% endfor %}
	{% else %}
	<p>No active agents.</p>
	{% endif %}
</div> <!-- AgentList -->